### ISSUE TITLE
Use Github Actions to Build

### ISSUE THREAD

**Issue by naveen521kk** [preshing/cairo-windows#11] opened 2020-08-27 15:22 UTC
I see @stuaxo setting up a script to update dependencies. Also, I prefer setting up a CI(May be Github Actions) to build and release when anything is updated. This would help us maintain the version of Cairo to latest and can be automated.

I tried https://github.com/naveen521kk/cairo-windows/runs/1037141588. Maybe if @preshing help me we can complete this easily.

**Comment by preshing** [comment] 2020-08-27 19:08
Out of curiosity, why do you and @stuaxo want such bleeding-edge cairo-windows builds? Cairo doesn't change that much from one version to the next. That why I've been happy just running it manually once in a while. Maybe your needs are different from mine.

Nonetheless, if you can get it working with a CI in your fork, that would be cool. Though I expect it will continue to break occasionally as the build tools & dependencies change.

According to the log you linked, `devenv.com "projects\vstudio\vstudio.sln" -upgrade` fails because `vstudio.sln` (in the libpng archive, downloaded from https://download.sourceforge.net/libpng/libpng-1.6.37.tar.gz) doesn't need to be upgraded. That's a strange error message because `vstudio.sln` is a VS2010 file (!) which normally can't be used by VS2017 unless upgraded.

Even stranger is that I don't get that error message when I perform the build steps on my local machine.

One difference I see is that in the GitHub Actions log, the Visual Studio version info is:
```
Microsoft Visual Studio 2017 Version 15.0.28307.1234.
```
whereas on my local machine, it's:
```
Microsoft Visual Studio 2017 Version 15.0.28307.1146.
```
I don't know if that's enough to explain the difference. Maybe there are other differences that I've missed too.

**Comment by preshing** [comment] 2020-08-27 19:18
I upgraded my VS2017. It's now the same version as in the GitHub Actions log:
```
Microsoft Visual Studio 2017 Version 15.0.28307.1234.
```
Still, I can't reproduce the error message locally. 🤔

**Comment by naveen521kk** [comment] 2020-08-27 19:25
> Out of curiosity, why do you and @stuaxo want such bleeding-edge cairo-windows builds?

Yes we wanted to depend on the DLL provided see https://github.com/pygobject/pycairo/pull/191 and that's why we wanted 
- Cairo up to date.
- Enable tee surface

**Comment by naveen521kk** [comment] 2020-08-27 19:33
@preshing I suspect this is because maybe I had to manually add the path, and if I set it to inherit it shows a `cygwin.dll` error in mysys terminal. So I manually added the path. See https://github.com/naveen521kk/cairo-windows/blob/90803ab0858832273e2b28648ca2c12ef0b59204/.github/workflows/build.yml#L26 . Maybe that's the issue. But really I don't know. Also, maybe let's configure it to work with VS2019 also.

**Comment by stuaxo** [comment] 2020-08-28 00:47
@preshing it's for pycairo which is language bindings for cairo + tends to track the latest cairo version.

@naveen521kk 
I think what might be tricky here adding the 64 bit build target using just the commandline.

The README shows how to add the x64 target via the IDE, can this be done on the commandline ?

**Comment by naveen521kk** [comment] 2020-08-28 03:10
> The README shows how to add the x64 target via the IDE, can this be done on the commandline

I don't know about that.

**Comment by naveen521kk** [comment] 2020-08-28 16:59
I just on googleing found that there is file located at `C:\Program Files (x86)\Microsoft Visual Studio\2017\community\Common7\tools\VsDevCmd.bat` which will add the path variables. Maybe I will try that instead of manually adding and check for it.

**Comment by stuaxo** [comment] 2020-08-29 00:48
Have a go if you get a chance.  I will get back to this in the next few days now.

The main issue seems to be that the solutions(s?) need the x64 target adding to them, which seems to need the IDE afaict.

Once it's added you can choose it and build x64 whenever.

Maybe we should add it, the upstream that to libpng and whichever of the others (ie zlib) that need if, then we can build them here without needing the manual step.

It's def something I want to try depending on how much free time I can get.

I think this is the last of the yaks to shave :)

**Comment by naveen521kk** [comment] 2020-09-01 17:56
I don't think I will be having time to look into this. Sorry.

**Comment by stuaxo** [comment] 2020-09-01 23:25
> I don't think I will be having time to look into this. Sorry.

No problem, you've done loads of bits already - if I get some try and do this, but could be a while.

**Comment by naveen521kk** [comment] 2020-10-07 18:22
Used some effort to make this and I could actually pretty much run in [Appveyor](https://ci.appveyor.com/project/naveen521kk/cairo-windows/builds/35621124) today. All deps build it well but sadly cairo failed. If anyone could help me we can set it up to build it. @preshing could you help me here? After that, a PR would automatically build it and publish.

**Comment by stuaxo** [comment] 2020-10-07 18:28
I need to catch up and remember what didn't work on this again.

In appveyor something weird is getting passed to link.exe
https://ci.appveyor.com/project/naveen521kk/cairo-windows/builds/35621124#L681

**Comment by naveen521kk** [comment] 2020-10-07 18:31
Possibly because Makefile.win32 is not edited properly? There should be some copypasta mistake there I 🤔. But need check it. Because I change it to a powershell script.

**Comment by naveen521kk** [comment] 2020-10-07 18:34
Also, is it possible to use meson here?

**Comment by stuaxo** [comment] 2020-10-07 18:38
Nice... what's the best way to grab your stuff so I can try running it locally, is there a .appveyor directory somewhere ?

Meson, would be fantastic - it looks like it may well be possible
https://gist.github.com/demotomohiro/25f4d86c5b3a90baa8c1a77806c40bd9

**Comment by naveen521kk** [comment] 2020-10-07 18:45
Here you go https://github.com/naveen521kk/cairo-windows/blob/test-appveyor1/appveyor.yml

**Comment by naveen521kk** [comment] 2020-10-07 18:46
> Meson, would be fantastic - it looks like it may well be possible

I suggest we should use that.

**Comment by naveen521kk** [comment] 2020-10-07 18:49
Also, I could use msys2 because is some kind of 404 happening. Maybe the site is down today. So, I installed make from chocolatey. That could be a possible problem.

**Comment by stuaxo** [comment] 2020-10-07 18:54
That's annoying, probably temporary ?

Any chance of adding comments above the sed commands on this, as I'm not sure what they enable, without having to remember a bunch of stuff !
https://github.com/naveen521kk/cairo-windows/blob/test-appveyor1/build-cairo.ps1

If I get some time I might try poking the github gist I linked to build with meson, but quite a lot of work on so not sure how much I help I will be able to give.

**Comment by naveen521kk** [comment] 2020-10-07 18:56
> Any chance of adding comments above the sed commands on this, as I'm not sure what they enable, without having to remember a bunch of stuff !

That can be done once it works. Also, those was just some copy paste of original script.

**Comment by stuaxo** [comment] 2020-10-07 19:56
Heh, I really meant so I could know what they do now :)

Are they the diffs to make them compile the 64 bit versions ?

**Comment by naveen521kk** [comment] 2020-10-09 04:45
I think [this doc](https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=vs-2019#developer_command_file_locations) tells about it. But need to test it first. @stuaxo 
Any update on that? Use make from, msys also fails. Looks like I need to try it once locally to know what those sed commands do.

**Comment by stuaxo** [comment] 2020-10-09 13:22
I'm not sure when I'm going to get a chunk of time to test stuff.
You can pass an architecture to `vcvarsall.bat` passing an architecture, `x86` and `x64` do the same thing as opening the 32 or 64 bit visual studio tools prompt.


I tried installing meson from pip the other and it seemed promising.   I copied the cairo bits from the gist above 

```shell
git clone --depth 1 https://gitlab.freedesktop.org/cairo/cairo.git
meson --prefix=c:\path\to\install --buildtype release -D tests=disabled -D gl-backend=disabled cairo_builddir cairo
meson compile -C cairo_builddir
meson install -C cairo_builddir
```

It got quite far, I wasn't really sure what to substitute for path to install, meson seemed to build zlib for itself which was nice.

**Comment by naveen521kk** [comment] 2020-10-09 13:28
You could see I had tried the same on appveyor also. https://ci.appveyor.com/project/naveen521kk/cairo-windows/builds/35659632

https://ci.appveyor.com/api/buildjobs/o02owbr68a1bmg1e/artifacts/cairo%2Fcairo.zip to src folder. I just used what they did in their CI though.

**Comment by naveen521kk** [comment] 2020-10-30 14:56
@stuaxo Found out what happened, it was called `link` from msys2 and not from msvc that caused the problem. After slight path manipulation that simply worked. 
I found the script already does it but there was a slight problem with that I think.

**Comment by stuaxo** [comment] 2020-10-30 17:57
I might be able to work out what the script does if I have any time, fiddling with PATHs etc shouldn't be *too* much hassle, especially if it's just to get the MSYS stuff earlier in the PATH.

**Comment by naveen521kk** [comment] 2020-10-30 18:06
I tried something and let me see if https://github.com/naveen521kk/cairo-windows/runs/1333429021?check_suite_focus=true works. If yes, done. 
Update: failed.

**Comment by naveen521kk** [comment] 2020-10-30 18:09
Also, @stuaxo do you know how to make thing in meson? I tried some few days back but I get a lot of dll's not a single one. Do you know how to fix it?

**Comment by stuaxo** [comment] 2020-10-30 18:35
I'll need to have a play ...  I just bought the meson manual so should be some info there
https://meson-manual.com/

There's a basic tutorial here I'm looking at too
https://mesonbuild.com/Tutorial.html

**Comment by naveen521kk** [comment] 2020-10-30 18:38
bash is hard. Can you help me with path manipulation? It's git bash which runs it. 

Also, about meson, I had a working thing in `meson` branch in my repo but as I said it depends on many other dll. You could see it build in appveyor. @stuaxo

**Comment by stuaxo** [comment] 2020-10-30 18:49
No probs, I'll try and make some time to look at it.

**Comment by naveen521kk** [comment] 2020-10-30 19:12
I deleted the link from bash so as to make it not cause trouble simply. Let me see
https://github.com/naveen521kk/cairo-windows/runs/1333700331?check_suite_focus=true

**Comment by naveen521kk** [comment] 2020-10-30 19:16
Done Got 32-bit binaries to build easily. Next, I need to try for 64-bit.
https://github.com/naveen521kk/cairo-windows/suites/1428104040/artifacts/24030691

**Comment by naveen521kk** [comment] 2020-10-30 19:31
Huh, 64-bit is more hard. I get an error that the solution file is not configured for x64 build. https://github.com/naveen521kk/cairo-windows/runs/1333751977?check_suite_focus=true#step:4:1088 
Any, idea what to do? @stuaxo

**Comment by stuaxo** [comment] 2020-10-30 22:19
I'm not going to get much / any time to look at it tonight, in the meantime I'd set the option in bash to output each command before it runs `set +x` then we can see why devenv is complainiing.

**Comment by stuaxo** [comment] 2020-11-02 16:48
In the end I ended up having a look at crossroad https://pypi.org/project/crossroad/ it helps you setup cross compilation environments from Linux, including Windows binaries, I think this might be an easier option ?

Once we get it building in one environment with that it should do the rest.

It would mean moving to Linux for building, but this is probably less hassle than Windows in CI.


I'd have a look at the project home page, for instance once you've installed it, if you decide you want to target Windows 64 bit you run `crossroad -h w64` it tells you which packages to install, you do that and then you can use it to compile the project you want (in compiling, it just compiles the project in the usual  way, but uses the cross compiler instead).

**Comment by naveen521kk** [comment] 2020-11-02 16:59
>  I think this might be an easier option ?

That would simply complicate things AFAIK. Currently, I have working CI for generating x86 binaries and slight patch to it will get x64 also working or maybe look into other methods to generating soln files, for example, many projects support meson and also it generates soln files for us. Some time and debugging would simply get it working.

**Comment by stuaxo** [comment] 2020-11-02 17:32
I'll still have a look at the PATH issues, but think it could be a way forward in future, as it would avoid all VS completely (it calls out to autotools + gcc, or autotools + meson).

I got as far as reproducing the issue you were having. the clashing between the two linkers is a bit annoying.

**Comment by naveen521kk** [comment] 2020-11-02 17:44
> I got as far as reproducing the issue you were having. the clashing between the two linkers is a bit annoying.

I fixed it by deleting the one I don't need. 😜 Because it is a CI.

We can use meson, but the point we don't get a single dll file statically linked with all dependency.

**Comment by stuaxo** [comment] 2020-11-02 19:10
I think that is might be because the linking stage failed (I had a similar thing in Linux a while back).

**Comment by stuaxo** [comment] 2020-11-02 22:36
Heh, looks like deleting link.exe is a totally valid method, another page I saw renamed it to `link2.exe`

**Comment by naveen521kk** [comment] 2020-11-03 03:12
I think you have a working VS2017 at your place. If yes, help me with one thing.

Follow the thing is [README](https://github.com/preshing/cairo-windows#building-64-bit) and then upload the `sln` file somewhere where I can read, maybe lets simply make a patch file and I think it should work.

**Comment by stuaxo** [comment] 2020-11-13 20:20
I've attached the sln file for 64 bit.
[vstudio.zip](https://github.com/preshing/cairo-windows/files/5539055/vstudio.zip)

Here is a 7zip of the whole folder after added 64 bit, you shouldn't need it, but it's just-in-case.
https://drive.google.com/file/d/1qEKv5J6RNf4DANvaGnJoAh9ejrpyVH2G/view?usp=sharing

I'll try adding the ARM targets afterwards if this works.

**Comment by stuaxo** [comment] 2020-11-19 19:57
I tried to understand libpng 64 bit issue a bit by creating a Windows 7 VM with VS 2010 and see if I could upstream a solution.

It turns out that the .sln format changed quite drastically, between then and the one that we patch.
Originally XML file, and adding x64 adds several lines.

It also looks like Microsoft plans on changing the format again the future.

Given this, the solution of patching the SLN works, but only for now.


There is also the issue here, about moving to meson:
https://github.com/preshing/cairo-windows/issues/12


In my usual Win 10 VM I had a play with Meson, and got it to output a dll.


In the VS tools prompt:

Assuming the VS build tools are in the PATH, create a directory named `build` configured to use VS:

`meson build --backend=vs`

I was able to compile, using:

`meson compile -C build`

(I think ninja -C build should have worked here, but it didn't for me).

This generates compiles a DLL and LIB in build\src
```
dir build\src\*.dll build\src\*.lib
 Volume in drive C has no label.
 Volume Serial Number is 7E90-E6EE

 Directory of C:\Users\Stu\Desktop\projects\external\cairo\build\src

19/11/2020  19:12         2,376,192 cairo-2.dll

 Directory of C:\Users\Stu\Desktop\projects\external\cairo\build\src

19/11/2020  19:12           102,440 cairo.lib
               2 File(s)      2,478,632 bytes
               0 Dir(s)     129,499,136 bytes free

```


These look about the right size, though I don't have time to test.


So I guess, the build could work by creating a `build-x86` and `build-x64` directories for each architecture, then grab the files it needs from these.

**Comment by naveen521kk** [comment] 2020-11-20 03:51
I don't think it will be statically linked though. I had quite a few experiences playing around it. See [this](https://github.com/naveen521kk/pango-build/blob/v1.47.0/ci/win/build.ps1). I would rather be happy if they are statically linked though. Any idea how to do that?

**Comment by naveen521kk** [comment] 2020-11-20 06:27
I tried that sln just today and it looks like it needs the same of zlib also along with libpng. https://github.com/naveen521kk/cairo-windows/runs/1429013550?check_suite_focus=true#step:4:1090

**Comment by stuaxo** [comment] 2020-11-20 10:32
Can you try the meson build?

It was straightforward when I tried to get it to build a DLL, I'm just not sure if it's one that works, though it should. 

The key is `backend=vs`, see above.

I can convert these, but probably not any free time for a few days to do it.

**Comment by stuaxo** [comment] 2020-11-20 10:35
I don't really know about static linking, the DLL looks about the same size though?

I guess you want to static link all it's dependencies?
Best thing is to build it and check, I'm writing this from my phone but prob won't be front of VS for a few days.

**Comment by naveen521kk** [comment] 2020-11-20 10:46
I simply tried up Dependency Walker, isolated it separately. Finally, on seeing it couldn't find many dependencies.

**Closed as completed** 2022-11-29 13:35 UTC
